# Tarea día 8
**Programación I**

In [7]:
import numpy as np

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [290]:
filas=4
colum=4

A=np.zeros([filas, colum])

In [291]:
b=A.flatten()
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [292]:
a=int(len(b)/2)
a

8

In [293]:
b[:a]=1
b

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [294]:
np.random.shuffle(b)
b

array([1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.])

In [295]:
C= b.reshape(filas,colum)
C

array([[1., 1., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.]])

# Ejercicio 1 otra vez

In [296]:
filas=10
colum=10
X= np.zeros(filas*colum)

In [297]:
y=np.arange(100)

In [298]:
z=np.random.choice(y, int((10*10)/2), replace=False)
z

array([54, 40, 52, 78, 94, 99, 63, 21,  0, 36, 53, 51, 25, 19,  6, 89, 18,
       24, 39, 55, 32, 44, 86, 95,  8, 28,  9, 38, 29, 43, 84, 71, 56, 27,
       79,  3, 87, 34, 48, 30, 91, 97, 83, 20, 14, 50, 69,  7, 35, 11])

In [299]:
X[z]=1
X

array([1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1.])

In [300]:
X.reshape(filas,colum)

array([[1., 0., 0., 1., 0., 0., 1., 1., 1., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1., 1., 0., 1., 1., 1.],
       [1., 0., 1., 0., 1., 1., 1., 0., 1., 1.],
       [1., 0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1., 0., 1., 1., 0., 1.],
       [0., 1., 0., 0., 1., 1., 0., 1., 0., 1.]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 


In [78]:
#inciso1
#Generando las matrices de 0 y 1 
zero=np.zeros((5,2))
one=np.ones((5,2))

print(zero)

print(one)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [81]:
#generando el vector columna
X=zero.flatten()
VecColum=X[:,None]
VecColum

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [82]:
#Generando el vector columna
Y=one.flatten()
VecColum2=Y[:,None]
VecColum2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [84]:
#Inciso2
#np.dstack genera un sepejo de 0s y 1s 
apilacion = np.dstack((VecColum,VecColum2))
apilacion

array([[[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]],

       [[0., 1.]]])

In [85]:
#Inciso 3

fila1= VecColum.flatten()
fila1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
fila2= VecColum2.flatten()
fila2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
np.concatenate(((fila1[:,None],fila2[:,None])),axis=0)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios, donde cada columna sea una variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una vector columna. 

In [3]:
random=np.random.randint(10 ,size=(10, 3))
random

array([[9, 8, 9],
       [3, 4, 9],
       [8, 9, 7],
       [8, 3, 4],
       [4, 8, 9],
       [3, 7, 7],
       [6, 3, 8],
       [4, 2, 3],
       [8, 8, 4],
       [8, 8, 6]])

In [4]:
def f(matriz):
    return 2*(matriz[:, 0]) + 3*(matriz[:, 1]) + matriz[:, 2]**2

In [5]:
f(random)

array([123,  99,  92,  41, 113,  76,  85,  23,  56,  76])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [494]:
fila1=50
colum1=50

cuadrado = np.random.randint(0, 2, ([fila1,colum1]))
cuadrado

array([[0, 0, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 1, 0],
       [1, 0, 1, ..., 1, 1, 1]])

In [496]:
cuadrado2 = cuadrado[20:40, 20:40]
cuadrado2
#Genera solo el cuadrado que necesitamos.

array([[1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 0, 1,

In [498]:
areac= sum(cuadrado.flatten())
areac

1265

In [499]:
areac2= sum(cuadrado2.flatten())
areac2

191

In [507]:
area = (areac2/areac)
area

0.1509881422924901

In [508]:
area*2500

377.47035573122525

In [506]:
AreaReal = (20*20)/(50*50)
AreaReal

0.16

## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

# Inciso 1 Tarea

## 1.Array creations routines (31 comandos)
## ones and zeros

In [63]:
#1
np.empty(shape= [3,3], dtype=int)

#Regresa un nuevo array de 3 filas con 3 columnas

array([[1, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
#2
np.eye(N=4, M=4, k=0, dtype=int, order="C")

#N= numero de filas
#M= numero de columnas
#K= desplazamiento de la diagonal de unos
#dtype = tipo de dato que saldra en el retorno
#Order = como se guarda C: row-mayor F: colum-major

#Regresa una matriz en dos dimensiones donde en la diagonal es uno y lo demas ceros.
#

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [68]:
#3
np.identity(n=4, dtype=float)

#Genera la matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
#5
np.ones(shape=3, dtype=int)

#regresa una fila con 3 columnas llena de unos

array([1, 1, 1])

In [71]:
np.ones(shape=[3,3], dtype=float)

#regresa 3 filas y 3 columnas llena de unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.ones((2,1))

#regresa 2 filas y una columna llena de unos

array([[1.],
       [1.]])

In [76]:
#6
A=np.arange(10)
A

#Genera una fila con 10 columnas

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
#7
B= A.reshape((5,2))
B

#Le cambia el shape al array A colocando 5 filas y 2 columnas

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [81]:
#8
np.ones_like(B)

#Genera una matriz que es de la forma que tiene B llena de unos 

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [82]:
#9
np.zeros(shape=(3,2), dtype=float)

#Genera una matriz de 0 tipo float con 3 filas y dos columnas

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [83]:
#10
np.zeros_like(B)

#Regresa una matriz igual que la matriz B pero repleta de ceros

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [86]:
#11
np.full(shape=6, fill_value= 10)

#regresa un valor dentro de una matriz que querramos ponerle, pueden ser letra o funciones como np.inf

array([10, 10, 10, 10, 10, 10])

In [93]:
np.full(shape=(10,2), fill_value=[1,2])

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [94]:
np.full(shape=10, fill_value= "print")

array(['print', 'print', 'print', 'print', 'print', 'print', 'print',
       'print', 'print', 'print'], dtype='<U5')

In [96]:
#12
np.full_like(B, fill_value=1)

#Hereda la forma que tiene la matriz B y le agrega 1 en todos sus componentes
#CUIDADO CON EL dtype de la matriz que se ereda si fuera int, solo nos va a tomar la parte entera del fill_value

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [97]:
np.full_like(B, fill_value=0.1)
#CUIDADO CON EL dtype de la matriz que se ereda si fuera int, solo nos va a tomar la parte entera del fill_value

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [98]:
np.full_like(B, fill_value=0.1, dtype=np.double)

#Si se le pone el dtype anula el dtype heredado por B y ya se pueden ingresar otro dtype

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

## From Existin Data

In [99]:
#13
np.array(object = [1,2,3,4], dtype=float, copy=True)
#Regresa de una data existente (objet) un array. 

array([1., 2., 3., 4.])

In [100]:
#14
np.asarray(a=[(2,2),(3,3),(4,4)], dtype=float)

#a= entrada de datos, que pueden ser listas, listas of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.

array([[2., 2.],
       [3., 3.],
       [4., 4.]])

In [102]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
#15
np.asmatrix(data=A, dtype=None)

# regresa un array en forma de una matriz 

matrix([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [111]:
#16
D=np.array([[2,3],[4,5]])
D

array([[2, 3],
       [4, 5]])

In [114]:
matrix = np.asmatrix(D)
matrix

#No genera una copia si el inpuy es una matrix o un ndarray. Equivalente a usar np.matrix(data, copy=False)

matrix([[2, 3],
        [4, 5]])

In [115]:
#17
x=np.array([1,2,3])
y=x
z= np.copy(x)

#genera una copia de un array

In [116]:
x[0]

1

In [117]:
y[0]

1

In [118]:
z[0]

1

In [127]:
x[0]=10

In [129]:
x[0]

10

In [130]:
y[0]

10

In [131]:
z[0]

1

In [132]:
#18
z[0] == x[0]

#False, porque z copio a x cuando x tenia 1,2,3

False

In [133]:
sr= b"hola, mundo"

In [147]:
#19
np.frombuffer(sr, dtype="S1", count=-1, offset=0)

#interpreta un string, que tiene un array de 1 dimensión

array([b'h', b'o', b'l', b'a', b',', b' ', b'm', b'u', b'n', b'd', b'o'],
      dtype='|S1')

In [150]:
#20
np.fromfunction(function= lambda i,j: i == j, shape=(5,5), dtype=int )

#desde una función se le puede pedir que genere un array que cumpla con la función

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [165]:
#21
iterable = (x**2 for x  in range(5))
np.fromiter(iterable, dtype=int, count=-1)

#Genera un array desde un iterable

#count = -1 lee todo, 0 no lee ninguno 1 lee el primero, 2 el segundo y así

array([ 0,  1,  4,  9, 16])

In [180]:
sr2= "1,2,3,4,5"

In [182]:
#22
ejemplo = np.fromstring(string=sr2, dtype=int, count=-1, sep=",")
ejemplo

#Regresa un array desde un str

array([1, 2, 3, 4, 5])

In [185]:
#23
ejemplo.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

# Building matrices

In [204]:
#24
ejmatrix= np.arange(9).reshape(3,3)
ejmatrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [214]:
#25
np.diag(ejmatrix, k=0)
#Regresa la diagonal de una matrix cuadrada 

#k=0 regresa la diagonal principal, 1 regresaria la diagonal elevada un puesto, -1 regresa diagonal inferior 1 puesto

array([0, 4, 8])

In [209]:
np.diag(np.diag(ejmatrix))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [202]:
ejmatrix2= np.arange(10).reshape(5,2)
ejmatrix2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [216]:
np.diag(v=ejmatrix2)

# CUIDADO solo regresa la diagonal de la primera matriz cuadrada 2x2 

array([0, 3])

In [219]:
#26
np.diagflat(v=ejmatrix, k=0) 
#pone los valores de una matrix, en la diagonal principal

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8]])

In [225]:
#27
np.tri(N=5, M=5, k=0, dtype=int)

#genera una matriz triangular
#N= numero de filas
#M= numero de columnas
#k=posición de la diagonal principal llena de 1

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [231]:
#28
np.tril(m=[[1,2,3],[4,5,6],[7,8,9]], k=0)

#diagonalizar una matriz, donde sus componentes superiores sean 0

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [232]:
#29
np.triu(m=[[1,2,3],[4,5,6],[7,8,9]], k=0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

### 2.Array Manipulation routines  (29 comnados + 38 comandos) = 

In [237]:
#30
array1 = np.arange(10)
array2 = np.arange(10,20)

In [238]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [239]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [241]:
#31
np.copyto(dst=array1, src=array2, where=True)
array1
#Copia desde dos distintos array, y modifica el array que es destino 

#dst = destino de array
#src = a quien se copia
#where= no entendi

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [244]:
#32
np.shape(array1)

#Regresa el shape of a ray, si regresa int significa que es una lista, si regresa una tupla (N,M)

(10,)

# Changing array Shape

In [246]:
#33
np.reshape(a=array1, newshape=(5,2))

#cambia el tipo de shape de un array 
#a = el array que se quiera cambiar


array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [248]:
#34
np.ravel(a=array1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [251]:
#35
array1.flat[0]
#regresa el valor de la posicion 0 en el array1

10

In [253]:
#36
array3 = np.arange(10).reshape(5,2)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [256]:
#37
array3.flatten(order="C")
#Genera una lista con todos los elementos en el array llamado

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [257]:
array3.flatten(order="F")
#en orden que aparecen en las columnas

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

# Changing number of dimensions

# Changing kind of array

In [273]:
lista = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

In [274]:
#38
np.asarray(a=lista, dtype=float, order="C")
#Convierte una lista en un array

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [275]:
#39
np.asarray(a=lista, dtype=float, order="F")
#Convierte una lista en un array

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [277]:
#40
np.asanyarray(a=lista, dtype=int,order="F")
#Convierte una lista en un array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [279]:
#41
np.asfarray(a=lista, dtype=str)
#regresa un array pero siempre sera FLOAT

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [280]:
#42
np.asfortranarray(a=lista, dtype=int)
#Regresa un array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [281]:
#43
np.ascontiguousarray(a=lista, dtype=int)
#Reggresa un array, ndim >= 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [283]:
$44
# PARA EL CHEQUEO DE NANS of INFS 
np.asarray_chkfinite(a=lista, dtype=None, order="F")

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [285]:
lista2 = [1,2,3,4, np.nan]

In [286]:
np.asarray_chkfinite(a=lista2, dtype=None, order="F")

##genero el error y encontro que array contiene infs o NaNs. 

ValueError: array must not contain infs or NaNs

In [303]:
#45
np.asscalar(np.array([24]))

#regresa un array de formato escalar

24

int

# Joingin arrays

In [313]:
D= np.arange(10).reshape(5,2)
E= np.arange(10,20).reshape(5,2)

In [314]:
#46
np.concatenate((D,E), axis=0, out=None)

#genera un nuevo array concatenando las dos arrays

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [319]:
#47
np.stack((D,E), axis=1, out=None)

Es de la dimensión de dos porque agarra la columna

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [320]:
#48
np.stack((D,E), axis=0, out=None)
#de dimensi[on 1 porque agarra la fila]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [322]:
#49
Dflat = D.flatten()
Dflat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [323]:
Eflat = E.flatten()
Eflat

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [328]:
#50
np.concatenate((Dflat,Eflat), axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [330]:
#51
np.stack((Dflat,Eflat), axis=1)
#Regresa una por listas.

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [331]:
#52
np.stack((Dflat,Eflat), axis=0)
#Regresa una por listas.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [333]:
#53
np.column_stack((Dflat,Eflat))


array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [335]:
#54
np.dstack((Dflat,Eflat,Dflat,Eflat))
#concatenacion en 3 ejes, 

array([[[ 0, 10,  0, 10],
        [ 1, 11,  1, 11],
        [ 2, 12,  2, 12],
        [ 3, 13,  3, 13],
        [ 4, 14,  4, 14],
        [ 5, 15,  5, 15],
        [ 6, 16,  6, 16],
        [ 7, 17,  7, 17],
        [ 8, 18,  8, 18],
        [ 9, 19,  9, 19]]])

In [336]:
#55
np.hstack((Dflat,Eflat))
#Regrea un array en secuencia horizontal (columna de forma )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [337]:
#56

np.vstack((Dflat, Eflat))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [348]:
#57
A = np.ones((2,2), dtype=int)
B= A*2
A


array([[1, 1],
       [1, 1]])

In [352]:
#58
BLOC = np.block([A,B])
BLOC
#apila por bloques dentro de una matriz.

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

# Splitting arrays

In [379]:
#59
np.split(BLOC.flatten(), 8, axis=0)
#separacion de en arrays. 

[array([1]),
 array([1]),
 array([2]),
 array([2]),
 array([1]),
 array([1]),
 array([2]),
 array([2])]

In [390]:
#60
np.array_split(E, 2, axis=1)
#separacion en diferentes arrays 

[array([[10],
        [12],
        [14],
        [16],
        [18]]), array([[11],
        [13],
        [15],
        [17],
        [19]])]

In [391]:
D

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [392]:
E

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [395]:
#61
np.dsplit(D, 3)

#una forma de separar por 3 o mas dimensiones.

ValueError: dsplit only works on arrays of 3 or more dimensions

In [399]:
#62
np.hsplit(D, 2)
#separa un array en multiples sub arrays horizontalmente, (column wise)

[array([[0],
        [2],
        [4],
        [6],
        [8]]), array([[1],
        [3],
        [5],
        [7],
        [9]])]

In [407]:
#63
np.vsplit(D, 1)
#separa un array en multiples sub arrays verticalmente, (row wise)

[array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])]

# Tiling Arrays (Mosaico)

In [416]:
#64
np.tile(A=Dflat, reps=2)
#repite los valores de un array las veces que se le pidan

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [417]:
np.tile(A=D, reps=2)
#Repite los valores dentro de las filas.

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [420]:
D

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [422]:
#65
np.repeat(D, repeats=3, axis=0)

#Repite las veces que se le pidan por columna = 1 o fila = 0

array([[0, 1],
       [0, 1],
       [0, 1],
       [2, 3],
       [2, 3],
       [2, 3],
       [4, 5],
       [4, 5],
       [4, 5],
       [6, 7],
       [6, 7],
       [6, 7],
       [8, 9],
       [8, 9],
       [8, 9]])

# Adding and removing elements¶

In [426]:
#66
Delete = np.arange(0,20).reshape(5,4)
Delete

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [427]:
#67
np.delete(Delete, 3)
#elimino el numero 3 de Delete

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [428]:
Delete1 = np.arange(0,20).reshape(5,4)
Delete1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [431]:
np.delete(Delete1, (2,1), axis=0)
#en el parentesis le decimos que filas eliminar
#son filas porque el axis es =0
#axis=1 eliminaria la columna 2 y 1 

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Insertar elementos a un array

In [440]:
#68
np.insert(Delete1, [2,4], 20)
#insertando el valor 20 en el array 

array([ 0,  1, 20,  2,  3, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19])

In [448]:
array_vacio = np.array([], dtype=int)
array_vacio

array([], dtype=int32)

In [452]:
#69
np.append(array_vacio, [2,3,4,5,6], axis=None)
#agregando al final de un array

array([2, 3, 4, 5, 6])

In [453]:
array_vacio

array([], dtype=int32)

In [455]:
#70
resisearray = np.array([[2,3],[4,2]])
resisearray

array([[2, 3],
       [4, 2]])

In [456]:
#71
np.resize(resisearray, (4,1))
# se le cambia el size de la matriz 

array([[2],
       [3],
       [4],
       [2]])

In [458]:
#72
np.trim_zeros([0,1,2,0])
#elimina los ceros de una matriz dimension 1 

[1, 2]

In [459]:
#73
np.unique([1,1,2,3,3,4,5,5,6,60])
#regresa solo los valores que aparecen 1 vez. 

array([ 1,  2,  3,  4,  5,  6, 60])

# Rearranging elemnts (reorganizar elementos)

In [471]:
#74
reorg = np.arange(100).reshape(10,10)
reorg

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [464]:
#75
np.flip(reorg)
#le da la vuelta al orden en que aparecen los elementos en la matriz.

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [466]:
#76
np.fliplr(reorg)
#Reordena cada fila invirtiendola

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [467]:
np.flipud(reorg)
#reordena filas invirtiendolas, y le hace una vuelta a todo

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [474]:
np.roll(a=reorg, shift=(1,2), axis=None)

#puede cambiar el orden de cada fila, si se le pide por tupla

array([[97, 98, 99,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86],
       [87, 88, 89, 90, 91, 92, 93, 94, 95, 96]])

In [488]:
np.rot90([[1,2],[3,4]], k=1, axes=(0,1))
#le da un giro de 90 grados a la matriz

array([[2, 4],
       [1, 3]])

# String Operations 69+4=73

In [510]:
Dflat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [509]:
Eflat

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [516]:
np.char.multiply("1,2,3,4", 3)
#Genera una lista 

array('1,2,3,41,2,3,41,2,3,4', dtype='<U21')

In [521]:
np.char.mod("1,2,3,4", (1,3))
#copia el string

array(['1,2,3,4', '1,2,3,4'], dtype='<U7')

In [525]:
np.lower(Dflat)

AttributeError: module 'numpy' has no attribute 'lower'

# Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario .npy y .npz

In [2]:
import numpy as np

In [4]:
#Se genera un array se guarda en un archivo .npy
x=np.array([2,3,4,5,6])
np.save("ejemplobinario.npy",x)

In [5]:
#Se carga el archivo 
y=np.load("ejemplobinario.npy")
y

array([2, 3, 4, 5, 6])

In [9]:
#se generan dos nuevos array 
x2= np.array([2,3,4,5,6])
x3= np.array([1,2])

In [10]:
#Se guardan como .npz
np.savez("ejemplobinario.npz", a=x2, b=x3)

In [12]:
#Se carga el archivo .npz
c= np.load("ejemplobinario.npz")
c

In [13]:
#accediendo a la generacion de archivo
c["a"]

array([2, 3, 4, 5, 6])

In [14]:
c["b"]

array([1, 2])

# 3,Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto .txt:

In [17]:
x=np.array([1,2,3,4])
np.savetxt("texto1.txt", x, fmt="%f")
y=np.loadtxt("texto1.txt", dtype=float)

In [18]:
x

array([1, 2, 3, 4])

In [19]:
y

array([1., 2., 3., 4.])

# Crear una función llamada estimacionMCO que lea un archivo CSV con 7 columnas, que corresponden a las variables  (𝑥1𝑖,…,𝑥6𝑖)  y  𝑦𝑖 .

La función debe computar matricialmente los parámetros del modelo de regresión lineal:  𝑦=𝑋𝛽 .

Estos parámetros deben ser devueltos como un arreglo de NumPy.

Utilice la función de lectura de archivos de NumPy.

In [8]:
matrix = np.random.randint(10, size=(10,7))
matrix

array([[1, 0, 8, 4, 0, 3, 3],
       [4, 9, 0, 5, 2, 8, 1],
       [3, 2, 2, 4, 0, 5, 3],
       [7, 7, 0, 3, 4, 6, 7],
       [6, 3, 6, 9, 2, 2, 1],
       [4, 2, 4, 2, 4, 5, 4],
       [5, 4, 0, 2, 5, 2, 5],
       [7, 9, 9, 2, 3, 0, 6],
       [8, 7, 5, 0, 5, 6, 4],
       [7, 6, 7, 4, 2, 2, 9]])

In [9]:
vecX = matrix[:,0:6]
vecX

array([[1, 0, 8, 4, 0, 3],
       [4, 9, 0, 5, 2, 8],
       [3, 2, 2, 4, 0, 5],
       [7, 7, 0, 3, 4, 6],
       [6, 3, 6, 9, 2, 2],
       [4, 2, 4, 2, 4, 5],
       [5, 4, 0, 2, 5, 2],
       [7, 9, 9, 2, 3, 0],
       [8, 7, 5, 0, 5, 6],
       [7, 6, 7, 4, 2, 2]])

In [12]:
vecY = matrix[:,6:7]
vecY

array([[3],
       [1],
       [3],
       [7],
       [1],
       [4],
       [5],
       [6],
       [4],
       [9]])

In [13]:
np.savetxt("MCO.csv",matrix, delimiter=",")

In [14]:
csv = np.loadtxt("MCO.csv", delimiter=",")
csv

array([[1., 0., 8., 4., 0., 3., 3.],
       [4., 9., 0., 5., 2., 8., 1.],
       [3., 2., 2., 4., 0., 5., 3.],
       [7., 7., 0., 3., 4., 6., 7.],
       [6., 3., 6., 9., 2., 2., 1.],
       [4., 2., 4., 2., 4., 5., 4.],
       [5., 4., 0., 2., 5., 2., 5.],
       [7., 9., 9., 2., 3., 0., 6.],
       [8., 7., 5., 0., 5., 6., 4.],
       [7., 6., 7., 4., 2., 2., 9.]])

In [16]:
MY=csv[:,6:7]
MY

array([[3.],
       [1.],
       [3.],
       [7.],
       [1.],
       [4.],
       [5.],
       [6.],
       [4.],
       [9.]])

In [17]:
MX=csv[:,0:6]
MX

array([[1., 0., 8., 4., 0., 3.],
       [4., 9., 0., 5., 2., 8.],
       [3., 2., 2., 4., 0., 5.],
       [7., 7., 0., 3., 4., 6.],
       [6., 3., 6., 9., 2., 2.],
       [4., 2., 4., 2., 4., 5.],
       [5., 4., 0., 2., 5., 2.],
       [7., 9., 9., 2., 3., 0.],
       [8., 7., 5., 0., 5., 6.],
       [7., 6., 7., 4., 2., 2.]])

In [18]:
XTRANS=MX.T
XTRANS

array([[1., 4., 3., 7., 6., 4., 5., 7., 8., 7.],
       [0., 9., 2., 7., 3., 2., 4., 9., 7., 6.],
       [8., 0., 2., 0., 6., 4., 0., 9., 5., 7.],
       [4., 5., 4., 3., 9., 2., 2., 2., 0., 4.],
       [0., 2., 0., 4., 2., 4., 5., 3., 5., 2.],
       [3., 8., 5., 6., 2., 5., 2., 0., 6., 2.]])

In [24]:
xtransx=XTRANS@MX
xtransx

array([[314., 298., 218., 171., 164., 196.],
       [298., 329., 188., 155., 154., 202.],
       [218., 188., 275., 148.,  94., 110.],
       [171., 155., 148., 175.,  72., 130.],
       [164., 154.,  94.,  72., 103., 108.],
       [196., 202., 110., 130., 108., 207.]])

In [25]:
beta=np.linalg.inv(xtransx)@XTRANS@MY
beta

array([[ 0.96994851],
       [-0.11570526],
       [ 0.15918549],
       [-0.24712832],
       [-0.15589774],
       [ 0.06142893]])

In [29]:
answY = MX@beta
answY

array([[1.43920594],
       [1.78244102],
       [2.31543734],
       [4.9833004 ],
       [4.01459573],
       [3.47442253],
       [3.23603404],
       [6.21901182],
       [7.3346636 ],
       [6.03225556]])

In [30]:
def estimacionMCO():
    csv=np.loadtxt("MCO.csv", delimiter=",")
    MY=csv[:,6:7]
    MX=csv[:,0:6]
    XTRANS=MX.T
    xtransporx=XTRANS@MX
    beta=np.linalg.inv(xtransporx)@XTRANS@MY
    AnswY=MX@beta
    return AnswY

In [27]:
estimacionMCO()

array([[1.43920594],
       [1.78244102],
       [2.31543734],
       [4.9833004 ],
       [4.01459573],
       [3.47442253],
       [3.23603404],
       [6.21901182],
       [7.3346636 ],
       [6.03225556]])